# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
#language: de_core_news_md
language: de_core_news_md
pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
   #- name: LanguageModelFeaturizer
   - name: SpacyNLP
   - name: SpacyTokenizer
   - name: SpacyFeaturizer   
#   - name: WhitespaceTokenizer
   - name: RegexFeaturizer #ist für look up tabels verantwortlich
     use_lookup_tables: True
   - name: SpacyEntityExtractor
     dimensions: [ "PERSON" ]
   - name: RegexEntityExtractor
     case_sensitive: False
     use_lookup_tables: True
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: DIETClassifier
     epochs: 200
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 100
   - name: FallbackClassifier
     threshold: 0.4
     ambiguity_threshold: 0.1
 #  - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1
 #  - name: supervised_embeddings
#ist gut. Multible intents sind nur mit der Pipline mölich

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
# CountVectors... EmbeddingInten.... brauche ich nicht mehr. Das ist da zu da falls ich zwei befehle gleichzeitig bekomme und erkennen muss z.B. Hallo hol mir einen Apfel [greed]+[bring]. Das habe ich aber momentan noch nicht. Ich lasse es trotzdem mal drin
#  - name: "FormPolicy" ich benutze die garnicht und mach bei upgrade zu 2.0 fehler

policies:
  - name: MemoizationPolicy #remembers story from training data
    max_history: 3
  - name: TEDPolicy
    epochs: 20
    constrain_similarities: True
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  #- name: "FallbackPolicy"
  #  nlu_threshold: 0.4
  #  core_threshold: 0.3
  #  fallback_action_name: "action_default_fallback"
#  - name: MappingPolicy
